const express=require('express')
const app=express()
const routerList=[
    {
      path: '/',
      name: 'Home',
      title:'首页',
      component: 'BasicLayout',
      children:[
        {
          path:'/happy',
          name:'Happy',
          component:'RouteView',
          title:'开心',
          icon:'el-icon-location',
          children:[
            {
              path:'/happy/happya',
              name:'Happya',
              title:'开心a',
              icon:'el-icon-time',
              component:'Happya'
            },
            {
              path:'/happy/happyb',
              name:'Happyb',
              title:'开心b',
              icon:'el-icon-mic',
              component:'Happyb'
            }
          ]
        },
        {
          path:'/list',
          name:'List',
          component:'RouteView',
          title:'列表',
          icon:'el-icon-stopwatch',
          children:[
            {
              path:'/list/lista',
              name:'Lista',
              title:'列表a',
              icon:'el-icon-discover',
              component:'Lista'
            },
            {
              path:'/list/listb',
              name:'Listb',
              title:'列表b',
              icon:'el-icon-lock',
              component:'Listb'
            }
          ]
        },
        {
          path:'/system',
          name:'System',
          component:'RouteView',
          title:'系统',
          icon:'el-icon-baseball',
          children:[
            {
              path:'/system/drnk',
              name:'Drnk',
              component:'RouteView',
              title:'喝',
              icon:'el-icon-moon',
              children:[
                {
                  path:'/system/drnk/drnka',
                  name:'Drnka',
                  title:'喝a',
                  icon:'el-icon-sunny',
                  component:'Drnka'
                },
                {
                  path:'/system/drnk/drnkb',
                  name:'Drnkb',
                  title:'喝b',
                  icon:'el-icon-cloudy',
                  component:'Drnkb'
                }
              ]
            },
            {
              path:'/system/eat',
              name:'Eat',
              title:'吃',
              icon:'el-icon-burger',
              component:'Eat'
            }
          ]
        }
      ],
    },
]
app.get('/user',(req,res)=>{
    res.json({code:200,message:'登陆成功',data:{routerList,token:'hahahahaha'}})
})
app.listen('9028')